kind: Deployment
apiVersion: apps/v1
metadata:
   name: frontend-deployment
   namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend-deployment
  template:
    metadata:
      name: frontend-deployment
      labels:
        name: frontend-deployment
    spec:
      containers:
        - name: frontendpod
          # image: bhasmeht/bookstoreimage:1.1.5 # {"$imagepolicy": "flux-system:frontend-podinfo"}
          image: bhasmeht/bookstoreimage:1.1.25
          ports:
            - containerPort: 80
