# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImageUpdateAutomation
# metadata:
#   name: frontend-app
# spec:
#   interval: 1m
#   sourceRef:
#     kind: GitRepository # the only valid value, but good practice to be explicit here
#     namespace: flux-system

# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImageUpdateAutomation
# metadata:
#   name: frontend-app 
#   namespace: flux-system
# spec:
#   git:
#     checkout:
#       ref:
#         branch: master
#     commit:
#       author: 
#         name: Bhaskar
#         email: bhaskarmehta422@gmail.com   
#   interval: 1m
#   sourceRef:
#     kind: GitRepository 
#     name: flux-system
#     namespace: flux-system    