kind: Service
apiVersion: v1 
metadata:
   name: frontend-svc 
   namespace: frontend
spec:
   selector:
        name: frontend-deployment  
   ports:
      - protocol: "TCP"
        port: 80
        targetPort: 80     
   type: LoadBalancer    